[versions]
janino = "3.1.12"
log4j2 = "2.25.3"
logback = "1.5.26"

[libraries]
janino = { module = "org.codehaus.janino:janino", version.ref = "janino" }
log4j-to-slf4j = { module = "org.apache.logging.log4j:log4j-to-slf4j", version.ref = "log4j2" }
logback = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }

[bundles]
common = [
    "janino",
    "log4j-to-slf4j",
    "logback",
]
