###############################
# ðŸ§© Version Catalog (Gradle)
###############################
[versions]
curator = "5.9.0"
jackson = "2.21.0"
kotlinpoet = "2.2.0"
ksp = "2.3.4"
org-apache-groovy = "5.0.4"
prometheus = "0.16.0"
protobuf = "4.33.4"

###############################
# ðŸ“¦ Libraries
###############################
[libraries]
# Utilities
agrona = "org.agrona:agrona:2.4.0"
# Akka & serialization
akka-kryo = "io.altoo:akka-kryo-serialization_2.13:2.5.2"
bcprov = "org.bouncycastle:bcprov-jdk15on:1.70"
# Other utilities
caffeine = "com.github.ben-manes.caffeine:caffeine:3.2.3"
curator-async = { module = "org.apache.curator:curator-x-async", version.ref = "curator" }
# Curator
curator-framework = { module = "org.apache.curator:curator-framework", version.ref = "curator" }
curator-recipes = { module = "org.apache.curator:curator-recipes", version.ref = "curator" }
easyexcel = "com.alibaba:easyexcel:4.0.3"
groovy = { module = "org.apache.groovy:groovy", version.ref = "org-apache-groovy" }
groovy-all = { module = "org.apache.groovy:groovy-all", version.ref = "org-apache-groovy" }
guava = "com.google.guava:guava:33.5.0-jre"
jackson-cbor = { module = "com.fasterxml.jackson.dataformat:jackson-dataformat-cbor", version.ref = "jackson" }
# Jackson
jackson-databind = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jackson" }
jackson-guava = { module = "com.fasterxml.jackson.datatype:jackson-datatype-guava", version.ref = "jackson" }
jackson-jdk8 = { module = "com.fasterxml.jackson.datatype:jackson-datatype-jdk8", version.ref = "jackson" }
jackson-jsr310 = { module = "com.fasterxml.jackson.datatype:jackson-datatype-jsr310", version.ref = "jackson" }
jackson-kotlin = { module = "com.fasterxml.jackson.module:jackson-module-kotlin", version.ref = "jackson" }
jackson-protobuf = { module = "com.fasterxml.jackson.dataformat:jackson-dataformat-protobuf", version.ref = "jackson" }
jackson-yaml = { module = "com.fasterxml.jackson.dataformat:jackson-dataformat-yaml", version.ref = "jackson" }
jcommander = "org.jcommander:jcommander:3.0"
# KotlinPoet & KSP
kotlinpoet = { module = "com.squareup:kotlinpoet", version.ref = "kotlinpoet" }
kotlinpoet-ksp = { module = "com.squareup:kotlinpoet-ksp", version.ref = "kotlinpoet" }
kryo = "com.esotericsoftware:kryo:5.6.2"
lz4 = "org.lz4:lz4-java:1.8.1"
mongodb-driver-sync = "org.mongodb:mongodb-driver-sync:5.6.2"
# Networking & compression
netty = "io.netty:netty-all:4.2.9.Final"
protobuf-java-util = { module = "com.google.protobuf:protobuf-java-util", version.ref = "protobuf" }
protobuf-kotlin = { module = "com.google.protobuf:protobuf-kotlin", version.ref = "protobuf" }
protoc = { module = "com.google.protobuf:protoc", version.ref = "protobuf" }
# Misc core libs
reflections = "org.reflections:reflections:0.10.2"
# Monitoring
simpleclient = { module = "io.prometheus:simpleclient", version.ref = "prometheus" }
simpleclient-hotspot = { module = "io.prometheus:simpleclient_hotspot", version.ref = "prometheus" }
simpleclient-httpserver = { module = "io.prometheus:simpleclient_httpserver", version.ref = "prometheus" }
# Spring & Mongo
spring-data-mongodb = "org.springframework.data:spring-data-mongodb:5.0.2"
spring-retry = "org.springframework.retry:spring-retry:2.0.12"
symbol-processing-api = { module = "com.google.devtools.ksp:symbol-processing-api", version.ref = "ksp" }

###############################
# ðŸ§º Bundles
###############################
[bundles]
curator = [
    "curator-async",
    "curator-framework",
    "curator-recipes",
]
jackson = [
    "jackson-databind",
    "jackson-guava",
    "jackson-jdk8",
    "jackson-jsr310",
    "jackson-kotlin",
]
prometheus = [
    "simpleclient",
    "simpleclient-hotspot",
    "simpleclient-httpserver",
]

###############################
# ðŸ”Œ Plugins
###############################
[plugins]
boot = "org.springframework.boot:4.0.2"
detekt = "io.gitlab.arturbosch.detekt:1.23.8"
dokka = "org.jetbrains.dokka:2.1.0"
foojay-resolver-convention = "org.gradle.toolchains.foojay-resolver-convention:1.0.0"
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
protobuf = "com.google.protobuf:0.9.6"
version-catalog-update = "nl.littlerobots.version-catalog-update:1.0.1"
