###############################
# ğŸ§ª Test Libraries Catalog
###############################

[versions]
junit = "5.9.3"

###############################
# ğŸ“¦ Libraries
###############################

[libraries]
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }
