###############################
# ðŸ§© KotlinX Version Catalog
###############################
[versions]
atomicfu = "0.31.0"
coroutines = "1.10.2"
datetime = "0.7.1"

###############################
# ðŸ“¦ Libraries
###############################
[libraries]
# --- AtomicFu ---
atomicfu = { module = "org.jetbrains.kotlinx:atomicfu", version.ref = "atomicfu" }
atomicfu-jvm = { module = "org.jetbrains.kotlinx:atomicfu-jvm", version.ref = "atomicfu" }
# --- Coroutines ---
core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
core-jvm = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core-jvm", version.ref = "coroutines" }
# --- DateTime ---
datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "datetime" }
datetime-jvm = { module = "org.jetbrains.kotlinx:kotlinx-datetime-jvm", version.ref = "datetime" }
