###############################
# üåê Ktor Version Catalog
###############################
[versions]
ktorClient = "3.4.0"
ktorServer = "3.4.0"

###############################
# üì¶ Libraries
###############################
[libraries]
ktor-client-cio = { module = "io.ktor:ktor-client-cio-jvm", version.ref = "ktorClient" }
# --- Ktor Client ---
ktor-client-core = { module = "io.ktor:ktor-client-core-jvm", version.ref = "ktorClient" }
ktor-serialization-jackson = { module = "io.ktor:ktor-serialization-jackson-jvm", version.ref = "ktorServer" }
ktor-server-content-negotiation = { module = "io.ktor:ktor-server-content-negotiation-jvm", version.ref = "ktorServer" }
ktor-server-cors = { module = "io.ktor:ktor-server-cors-jvm", version.ref = "ktorServer" }
ktor-server-host-common = { module = "io.ktor:ktor-server-host-common-jvm", version.ref = "ktorServer" }
# --- Ktor Server ---
ktor-server-netty = { module = "io.ktor:ktor-server-netty-jvm", version.ref = "ktorServer" }
ktor-server-request-validation = { module = "io.ktor:ktor-server-request-validation-jvm", version.ref = "ktorServer" }
ktor-server-status-pages = { module = "io.ktor:ktor-server-status-pages-jvm", version.ref = "ktorServer" }

###############################
# üß∫ Bundles
###############################
[bundles]
common = [
    "ktor-client-cio",
    "ktor-client-core",
    "ktor-serialization-jackson",
    "ktor-server-content-negotiation",
    "ktor-server-cors",
    "ktor-server-host-common",
    "ktor-server-netty",
    "ktor-server-request-validation",
    "ktor-server-status-pages",
]
